### ISSUE TITLE
Can not use AK8963

### ISSUE THREAD

**Issue by ttyyzz34** [tuupola/micropython-mpu9250#27]
Who can help me to solve the issue?
I can not find AK8963.
I use i2c.scan() get 
i2c.scan()
[60, 104, 118]
Can not find AK8963.
I use the AK8963.py and it give error like this:
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "ak8963.py", line 76, in init
  File "ak8963.py", line 139, in whoami
  File "ak8963.py", line 197, in _register_char
OSError: [Errno 19] ENODEV

**Comment by tuupola** [comment]
Although ENODEV suggest different error, looking at the scan resuts which in hex are 0x3c, 0x68 and 0x76. The address of AK8963 is 0x48. Are you sure you have an AK8963 connected to the bus?

**Comment by jchome** [comment]
Hello,
I've the same problem : 

```
  File "mpu6500.py", line 157, in whoami
  File "mpu6500.py", line 189, in _register_char
OSError: [Errno 19] ENODEV
```


I've connected the MPU with (I think) correct pins.

**Comment by tuupola** [comment]
What does `print(i2c.scan())` return?

**Comment by jchome** [comment]
> What does `print(i2c.scan())` return?

It returns an empty array : []

My pins seems to be wrong...

**Comment by jchome** [comment]
After a wire inversion, here is the response of `print(i2c.scan())`:
[104] 

I've then updated the `ak8963.py` file as mentioned in [pull request #31](https://github.com/tuupola/micropython-mpu9250/pull/31#issuecomment-2111939637)
Here is the last error:

```
  File "mpu9250.py", line 56, in __init__
  File "ak8963.py", line 78, in __init__
RuntimeError: AK8963 not found in I2C bus. 
```

So, i finally modified the `ak8963.py` file
from 
`if 0x48 != self.whoami:`
to
`if 0xcb != self.whoami:`

and the device was found:
`MPU9250 id: 0x70`

Thanks !
